// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBzHZQbYw0l2khafDBp9F8BPnE2PNw1E7g',
    appId: '1:827204439269:web:fdc10d51e54f42a278180c',
    messagingSenderId: '827204439269',
    projectId: 'cryptocoinflutter',
    authDomain: 'cryptocoinflutter.firebaseapp.com',
    storageBucket: 'cryptocoinflutter.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB7W0mXBas1SNpeW-TiHw41DeWeTFxgtiQ',
    appId: '1:827204439269:android:0e635ee19f91c84678180c',
    messagingSenderId: '827204439269',
    projectId: 'cryptocoinflutter',
    storageBucket: 'cryptocoinflutter.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA2NqnxjIy00ACcvRg_0aJVcC8e3jRNhxg',
    appId: '1:827204439269:ios:b12f97d23ec234eb78180c',
    messagingSenderId: '827204439269',
    projectId: 'cryptocoinflutter',
    storageBucket: 'cryptocoinflutter.appspot.com',
    iosBundleId: 'com.example.cryptocoin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA2NqnxjIy00ACcvRg_0aJVcC8e3jRNhxg',
    appId: '1:827204439269:ios:0d36cbcdd46b0fc178180c',
    messagingSenderId: '827204439269',
    projectId: 'cryptocoinflutter',
    storageBucket: 'cryptocoinflutter.appspot.com',
    iosBundleId: 'com.example.cryptocoin.RunnerTests',
  );
}
